# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: gandjustas' blog
header-img: img/home-bg.jpg
description: Обо всем понемногу
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.gandjustas.ru" # the base hostname & protocol for your site

twitter_username: gandjustas
github_username:  gandjustas
facebook_username: gandjustas
email_username: mail@gandjustas.ru


disqus-shortname:gandjustas

# Build settings
markdown: kramdown
kramdown:
    input: GFM

bootstrap:
    assets: true

permalink: pretty
paginate: 5

sass:
  style: compressed

exclude: ["node_modules","gulpfile.js","package.json","README.md", "Gemfile", "Gemfile.lock"]


gems: [jekyll-bootstrap-sass, jekyll-paginate, jekyll-feed] 
 
