# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: gandjustas' blog
header-img: img/home-bg.jpg
description: Блог о SharePoint, облаках, порталах, архитектуре, разработке и бизнесе. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.gandjustas.ru" # the base hostname & protocol for your site

# Site owner
owner:
  name: Стас Выщепан
  avatar: img/avatar.png
  bio: Автор, спикер, консультант, основатель и руководитель vnextsoft.
  email: mail@gandjustas.ru
  disqus-shortname: gandjustas
  twitter: gandjustas
  facebook: gandjustas
  yandex:
    metrika: 24750230
  google:
    plus: СтаниславВыщепан
    analytics: UA-27703615-1
    verify:
    ad-client:
    ad-slot:
  addthis: ra-4e28098f29c8a641
  bing-verify:
  github: gandjustas
  stackoverflow: 20655/gandjustas
  linkedin: gandjustas
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: gandjustas
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username



disqus-shortname: gandjustas

# Build settings
markdown: kramdown
kramdown:
    input: GFM

permalink: pretty
paginate: 5

sass:
  style: compressed

feed:
  path: atom.xml
   
exclude: ["node_modules","gulpfile.js","package.json","README.md", "Gemfile", "Gemfile.lock"]


gems: [jekyll-paginate, jekyll-sitemap,jekyll-redirect-from] 
 
